version: '3'

vars:
  BOARD: nice_nano_v2
  BUILD_DIR: "{{.ROOT_DIR}}/build"
  ZMK_APP: "{{.ROOT_DIR}}/zmk/app"
  WEST: python3 -m west
  TOOLCHAIN_PATH:
    sh: ls -d /Applications/ArmGNUToolchain/*/arm-none-eabi 2>/dev/null | head -1 || echo ""

env:
  ZEPHYR_TOOLCHAIN_VARIANT: gnuarmemb
  GNUARMEMB_TOOLCHAIN_PATH: "{{.TOOLCHAIN_PATH}}"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  init:
    desc: Initialize West workspace
    cmds:
      - brew install --cask gcc-arm-embedded || true
      - pip3 install west
      - "{{.WEST}} init -l config/ || true"
      - "{{.WEST}} update"

  build:left:
    desc: Build left board firmware
    dir: "{{.ZMK_APP}}"
    cmds:
      - "{{.WEST}} build -p -d {{.BUILD_DIR}}/left -b {{.BOARD}} -- -DSHIELD=gkey_left -DZMK_CONFIG={{.ROOT_DIR}}/config"
    sources:
      - "{{.ROOT_DIR}}/config/**/*"
    generates:
      - "{{.BUILD_DIR}}/left/zephyr/zmk.uf2"

  build:right:
    desc: Build right board firmware
    dir: "{{.ZMK_APP}}"
    cmds:
      - "{{.WEST}} build -p -d {{.BUILD_DIR}}/right -b {{.BOARD}} -- -DSHIELD=gkey_right -DZMK_CONFIG={{.ROOT_DIR}}/config"
    sources:
      - "{{.ROOT_DIR}}/config/**/*"
    generates:
      - "{{.BUILD_DIR}}/right/zephyr/zmk.uf2"

  build:all:
    desc: Build both left and right board firmware
    deps:
      - build:left
      - build:right

  clean:
    desc: Clean build directories
    cmds:
      - rm -rf {{.BUILD_DIR}}

  clean:left:
    desc: Clean left board build directory
    cmds:
      - rm -rf {{.BUILD_DIR}}/left

  clean:right:
    desc: Clean right board build directory
    cmds:
      - rm -rf {{.BUILD_DIR}}/right

  rebuild:left:
    desc: Clean and rebuild left board
    cmds:
      - task: clean:left
      - task: build:left

  rebuild:right:
    desc: Clean and rebuild right board
    cmds:
      - task: clean:right
      - task: build:right

  rebuild:all:
    desc: Clean and rebuild both boards
    cmds:
      - task: clean
      - task: build:all
